name: Master CI

on:
  workflow_dispatch:
#  push:
#    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest    

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml -P ossrh

  publish_central:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8 Apache Maven Central
      uses: actions/setup-java@v1
      with: # running setup-java again overwrites the settings.xml
        java-version: 1.8
        server-id: ossrh
        server-username: MAVEN_CENTRAL_USERNAME
        server-password: MAVEN_CENTRAL_TOKEN
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}

    - name: Publish to Apache Maven Central
      run: mvn deploy -Possrh
      env:
        MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      working-directory: vaadin-date-range-picker
  
  build_directory:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      
    - name: Build for Vaadin Directory
      run: mvn deploy -Pdirectory
      working-directory: vaadin-date-range-picker
      
    - name: Upload asset
      uses: actions/upload-artifact@v2
      with:
        name: vaadin-date-range-picker
        path: vaadin-date-range-picker/target/vaadin-date-range-picker-*.zip
        if-no-files-found: error
